const types = {
  FETCH_REPOS: "FETCH_REPOS",
  FETCHED_REPOS: "FETCHED_REPOS",
  RECEIVE_ERROR: "RECEIVE_ERROR",
  SET_SEARCH_PHRASE: "SET_SEARCH_PHRASE",
  INCREMENT_PAGE_COUNTER: "INCREMENT_PAGE_COUNTER",
  DECREMENT_PAGE_COUNTER: "DECREMENT_PAGE_COUNTER",
  LOAD_REPOSITORY_INFO: "LOAD_REPOSITORY_INFO",
  RECIEVE_REPOSITORY_INFO: "RECIEVE_REPOSITORY_INFO",
  FAIL_REPOSITORY_INFO: "FAIL_REPOSITORY_INFO",
  DOWNLOAD_REPOSITORY_README: "DOWNLOAD_REPOSITORY_README",
  RECIEVE_REPOSITORY_README: "RECIEVE_REPOSITORY_README",
  FAIL_README_DOWNLOAD: "FAIL_README_DOWNLOAD",
  FETCH_USER_REPOS: "FETCH_USER_REPOS",
  RECIEVE_USER_REPOS: "RECIEVE_USER_REPOS",
  FAIL_USER_REPOS: "FAIL_USER_REPOS"
};

export default types;
